[build]
  command = ""
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/wasm/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
